# GitHub Secret Scanning Configuration
# This file allows you to configure which secrets should be ignored

# Ignore Google API keys in google-services.json files
- name: "Google API Keys in google-services.json"
  pattern: "google-services.json"
  reason: "Required for Firebase/Google Services integration"

# Ignore keystore files (they are encrypted and password-protected)
- name: "Keystore files"
  pattern: "*.jks"
  reason: "Encrypted keystore files for app signing"

# Ignore password files (they contain encrypted passwords)
- name: "Password files"
  pattern: "*.pwd"
  reason: "Password files for keystore access"
